export const lawAndCreativeCareers = [
  {
    title: 'Corporate Lawyer',
    slug: 'corporate-lawyer',
    shortDescription: 'Advise businesses on legal rights, obligations, and corporate transactions.',
    description: 'Corporate Lawyers ensure that commercial transactions are legal, advising corporations on their legal rights and duties. In India, corporate law is highly lucrative, dealing with massive mergers and acquisitions (M&A), intellectual property rights, and foreign investments. It requires reading hundreds of pages of contracts, intense negotiation skills, and a solid understanding of business regulations.',
    category: 'Law',
    averageSalary: { entry: 800000, mid: 2000000, senior: 5000000 },
    requiredSkills: ['Contract Law', 'Negotiation', 'Attention to Detail', 'Corporate Law', 'Writing'],
    requiredEducation: ["BA LLB (5 years)", "LLB (3 years after graduation)", "LLM (Optional)"],
    eligibility: '10+2 any stream to appear for CLAT/AILET/LSAT for 5-year integrated course.',
    entranceExams: ['CLAT', 'AILET', 'LSAT India', 'MH CET Law'],
    topColleges: ['NLSIU Bangalore', 'NALSAR Hyderabad', 'NLU Delhi', 'NUJS Kolkata', 'Symbiosis Law School'],
    topCompanies: ['Cyril Amarchand Mangaldas', 'Khaitan & Co', 'AZB & Partners', 'Trilegal', 'Shardul Amarchand Mangaldas'],
    growthOutlook: 'High',
    demandLevel: 'High',
    workLifeBalance: 4,
    jobSatisfaction: 7,
    dayInLife: 'Drafting 100-page contracts, advising corporate boards on legal compliance, conducting due diligence for mergers, and long hours researching precedents.',
    riasecCodes: ['E', 'C', 'I'],
    roadmapSteps: [
      { step: 1, title: 'Foundation', description: 'Strong reading and debate skills in school.', duration: '2 yrs', skills: ['Debating', 'Reading Comprehension'], resources: ['Newspapers'] },
      { step: 2, title: 'Preparation', description: 'Prepare for CLAT/AILET in 11th/12th.', duration: '2 yrs', skills: ['Legal Aptitude', 'Logic'], resources: ['Universal Guide to CLAT', 'LegalEdge'] },
      { step: 3, title: 'Law School', description: '5-year BA LLB program at a top NLU. Do corporate internships.', duration: '5 yrs', skills: ['Moot Courts', 'Drafting'], resources: ['LiveLaw', 'Bar and Bench'] },
      { step: 4, title: 'Associate', description: 'Join a Tier-1 law firm as Junior Associate.', duration: '3-4 yrs', skills: ['Due Diligence'], resources: ['Firm seniors'] },
      { step: 5, title: 'Senior / Partner', description: 'Lead M&A deals and eventually become a Partner at the firm.', duration: 'Ongoing', skills: ['Client Acquisition', 'Negotiation'], resources: [] }
    ]
  },
  {
    title: 'Civil Lawyer',
    slug: 'civil-lawyer',
    shortDescription: 'Handle non-criminal legal disputes such as property, family, and contracts.',
    description: 'Civil Lawyers represent individuals or organizations in non-criminal disputes, such as property arguments, divorce proceedings, constitutional violations, and breach of contracts. Unlike corporate lawyers, civil lawyers spend a significant amount of time arguing in courtrooms (litigation). Building a successful private practice takes years of apprenticing under senior advocates.',
    category: 'Law',
    averageSalary: { entry: 300000, mid: 1000000, senior: 3000000 },
    requiredSkills: ['Litigation', 'Public Speaking', 'Legal Research', 'Persuasion', 'Patience'],
    requiredEducation: ["BA LLB", "LLB"],
    eligibility: '10+2 any stream followed by law entrance exams.',
    entranceExams: ['CLAT', 'State Law Entrances'],
    topColleges: ['NLUs', 'Government Law College (GLC) Mumbai', 'Faculty of Law DU'],
    topCompanies: ['Independent Practice', 'Boutique Litigation Firms', 'Chambers of Senior Advocates'],
    growthOutlook: 'Steady',
    demandLevel: 'Steady',
    workLifeBalance: 5,
    jobSatisfaction: 8,
    dayInLife: 'Arguing cases before judges in District/High Courts, drafting petitions and affidavits, advising clients on their rights, and filing paperwork at registries.',
    riasecCodes: ['E', 'I', 'S'],
    roadmapSteps: [
      { step: 1, title: 'Foundation', description: 'Read extensively about civics and politics.', duration: '2 yrs', skills: ['Reading'], resources: [] },
      { step: 2, title: 'Law School Prep', description: 'Clear CLAT or DU LLB entrance.', duration: '1-2 yrs', skills: ['Legal Reasoning'], resources: [] },
      { step: 3, title: 'Law Degree', description: 'Complete LLB. Participate heavily in Moot Court competitions.', duration: '3-5 yrs', skills: ['Mooting'], resources: [] },
      { step: 4, title: 'Chamber Devilling', description: 'Work as a junior under a Senior Advocate to learn court craft.', duration: '2-4 yrs', skills: ['Court Procedures'], resources: [] },
      { step: 5, title: 'Independent Practice', description: 'Take up independent briefs and establish your own legal practice.', duration: 'Ongoing', skills: ['Client Management', 'Litigation'], resources: [] }
    ]
  },
  {
    title: 'UX/UI Designer',
    slug: 'ux-ui-designer',
    shortDescription: 'Design intuitive, user-friendly interfaces for digital products.',
    description: 'User Experience (UX) and User Interface (UI) Designers ensure that digital products (apps, websites) are easy to use, visually appealing, and solve user problems. India\'s tech boom has created a massive demand for designers who understand human psychology and can create seamless digital journeys. It requires empathy, creativity, and an understanding of technology limits.',
    category: 'Creative & Design',
    averageSalary: { entry: 500000, mid: 1200000, senior: 2500000 },
    requiredSkills: ['Figma', 'User Research', 'Wireframing', 'Prototyping', 'Visual Design'],
    requiredEducation: ["B.Des", "Any Degree + Strong Portfolio"],
    eligibility: 'No strict degree barrier if portfolio is excellent. However, a B.Des from elite colleges provides a huge advantage.',
    entranceExams: ['UCEED', 'NID DAT'],
    topColleges: ['NID Ahmedabad', 'IIT Bombay (IDC)', 'Srishti Institute', 'MIT Pune'],
    topCompanies: ['Google', 'Cred', 'Zomato', 'Freshworks', 'Design Agencies'],
    growthOutlook: 'Very High',
    demandLevel: 'Very High',
    workLifeBalance: 7,
    jobSatisfaction: 8,
    dayInLife: 'Conducting user interviews, creating user journey maps, designing low-fidelity wireframes, building high-fidelity interactive prototypes in Figma, and handing off designs to developers.',
    riasecCodes: ['A', 'I', 'C'],
    roadmapSteps: [
      { step: 1, title: 'Foundation', description: 'Develop an eye for aesthetics and problem solving.', duration: '1 yr', skills: ['Observation', 'Empathy'], resources: ['Don\'t Make Me Think book'] },
      { step: 2, title: 'Learn Tools', description: 'Master Figma. Understand basic color theory and typography.', duration: '6 months', skills: ['Figma', 'UI Basics'], resources: ['YouTube', 'Google UX course'] },
      { step: 3, title: 'Portfolio Building', description: 'Redesign existing apps or create case studies for new app ideas.', duration: '1 yr', skills: ['UX Research', 'Prototyping'], resources: ['Behance', 'Dribbble'] },
      { step: 4, title: 'Junior Designer', description: 'Join a startup or agency. Learn to work with developers and PMs.', duration: '2 yrs', skills: ['Design Systems', 'Collaboration'], resources: [] },
      { step: 5, title: 'Senior / Lead Designer', description: 'Lead design teams, shape product strategy, and establish design culture.', duration: 'Ongoing', skills: ['Leadership', 'UX Strategy'], resources: [] }
    ]
  },
  {
    title: 'Graphic Designer',
    slug: 'graphic-designer',
    shortDescription: 'Create visual concepts to communicate ideas that inspire and inform.',
    description: 'Graphic Designers create visual concepts, using computer software or by hand, to communicate ideas that inspire, inform, and captivate consumers. They develop the overall layout and production design for advertisements, brochures, magazines, and corporate reports.',
    category: 'Creative & Design',
    averageSalary: { entry: 300000, mid: 700000, senior: 1500000 },
    requiredSkills: ['Adobe Creative Suite (Photoshop, Illustrator)', 'Typography', 'Branding', 'Creativity'],
    requiredEducation: ["B.F.A", "B.Des", "Any Degree + Portfolio"],
    eligibility: 'Portfolio matters more than the degree.',
    entranceExams: ['NID DAT (Optional)'],
    topColleges: ['NID', 'Sir J. J. Institute of Applied Art', 'Srishti Institute'],
    topCompanies: ['Ogilvy', 'Leo Burnett', 'Any corporate marketing team', 'Freelance'],
    growthOutlook: 'Moderate',
    demandLevel: 'High',
    workLifeBalance: 6,
    jobSatisfaction: 7,
    dayInLife: 'Meeting with clients/art directors, creating logos and brand guidelines, selecting typography, and designing social media graphics.',
    riasecCodes: ['A', 'R', 'E'],
    roadmapSteps: [
      { step: 1, title: 'Foundation', description: 'Learn basic art and colors.', duration: '1 yr', skills: ['Art'], resources: [] },
      { step: 2, title: 'Software', description: 'Learn Photoshop & Illustrator.', duration: '6 months', skills: ['Adobe CC'], resources: [] },
      { step: 3, title: 'Portfolio', description: 'Create sample brand identities.', duration: '1 yr', skills: ['Typography'], resources: [] },
      { step: 4, title: 'Junior Designer', description: 'Agency work.', duration: '2 yrs', skills: ['Speed', 'Client handling'], resources: [] },
      { step: 5, title: 'Art Director', description: 'Lead campaigns.', duration: 'Ongoing', skills: ['Creative Direction'], resources: [] }
    ]
  },
  {
    title: 'Architect',
    slug: 'architect',
    shortDescription: 'Plan and design buildings and other physical structures.',
    description: 'Architects blend art and science to design buildings and other structures. They are responsible for making structures safe, functional, and aesthetically pleasing. In India, rapid urbanization requires architects to balance modern design with sustainable (green building) practices and Vastu Shastra considerations.',
    category: 'Creative & Design',
    averageSalary: { entry: 300000, mid: 800000, senior: 2000000 },
    requiredSkills: ['AutoCAD', '3D Modeling (SketchUp, Revit)', 'Design Sense', 'Spatial Reasoning', 'Project Management'],
    requiredEducation: ["B.Arch (5 years)"],
    eligibility: '10+2 with PCM is mandatory. Must clear NATA or JEE Main Paper 2.',
    entranceExams: ['JEE Main Paper 2 (B.Arch)', 'NATA'],
    topColleges: ['School of Planning and Architecture (SPA) Delhi', 'CEPT University Ahmedabad', 'IIT Kharagpur', 'JJ College of Architecture'],
    topCompanies: ['Hafeez Contractor', 'CP Kukreja Architects', 'Morphogenesis', 'L&T Construction'],
    growthOutlook: 'Steady',
    demandLevel: 'Steady',
    workLifeBalance: 5,
    jobSatisfaction: 8,
    dayInLife: 'Drafting 2D/3D floor plans, visiting construction sites to ensure design compliance, meeting clients to discuss aesthetic preferences, and coordinating with structural engineers.',
    riasecCodes: ['A', 'I', 'R'],
    roadmapSteps: [
      { step: 1, title: 'Foundation', description: 'Develop sketching skills and spatial awareness.', duration: '2 yrs', skills: ['Drawing'], resources: [] },
      { step: 2, title: 'Preparation', description: 'Clear NATA/JEE Paper 2.', duration: '1 yr', skills: ['Aptitude', 'PCM'], resources: ['NATA prep books'] },
      { step: 3, title: 'B.Arch', description: '5-year rigorous degree focusing on design studios.', duration: '5 yrs', skills: ['AutoCAD', 'Design Theory'], resources: [] },
      { step: 4, title: 'Junior Architect', description: 'Work in an architectural firm.', duration: '3 yrs', skills: ['Execution', 'Client handling'], resources: [] },
      { step: 5, title: 'Principal Architect', description: 'Start your own firm or become a partner.', duration: 'Ongoing', skills: ['Business Development'], resources: [] }
    ]
  },
  {
    title: 'Fashion Designer',
    slug: 'fashion-designer',
    shortDescription: 'Create clothing, accessories, and footwear designs.',
    description: 'Fashion Designers study trends, sketch initial designs, select fabrics, and oversee the final production of garments. The Indian fashion industry is expanding globally, blending traditional ethnic wear with western silhouettes. It requires immense creativity, an eye for color and texture, and understanding of the textile business.',
    category: 'Creative & Design',
    averageSalary: { entry: 300000, mid: 800000, senior: 2500000 },
    requiredSkills: ['Sketching', 'Fabric Knowledge', 'Pattern Making', 'Trend Forecasting', 'CAD for Fashion'],
    requiredEducation: ["B.Des in Fashion Design"],
    eligibility: '10+2 in any stream. Admission to top institutes requires clearing aptitude and situation tests.',
    entranceExams: ['NIFT Entrance', 'NID DAT'],
    topColleges: ['NIFT (Delhi, Mumbai, etc.)', 'NID', 'Pearl Academy'],
    topCompanies: ['Sabyasachi', 'Manish Malhotra', 'FabIndia', 'Reliance Brands', 'Myntra'],
    growthOutlook: 'Steady',
    demandLevel: 'Moderate',
    workLifeBalance: 5,
    jobSatisfaction: 8,
    dayInLife: 'Sketching new collections, sourcing fabrics from markets, attending fittings, overseeing tailors, and planning fashion show presentations.',
    riasecCodes: ['A', 'E', 'R'],
    roadmapSteps: [
      { step: 1, title: 'Foundation', description: 'Sketch continuously.', duration: '2 yrs', skills: ['Sketching'], resources: [] },
      { step: 2, title: 'Preparation', description: 'Clear NIFT entrance.', duration: '1 yr', skills: ['Creative Aptitude'], resources: [] },
      { step: 3, title: 'Education', description: 'B.Des Fashion. Submit a final year collection.', duration: '4 yrs', skills: ['Pattern Making'], resources: [] },
      { step: 4, title: 'Assistant Designer', description: 'Work under an established designer or retail brand.', duration: '2-3 yrs', skills: ['Sourcing', 'Production'], resources: [] },
      { step: 5, title: 'Own Label', description: 'Launch your own fashion brand or head design for a retail giant.', duration: 'Ongoing', skills: ['Branding'], resources: [] }
    ]
  },
  {
    title: 'Journalist',
    slug: 'journalist',
    shortDescription: 'Research, write, and report news stories for various media outlets.',
    description: 'Journalists uncover the truth and report news to the public. In the digital age, journalists in India work across print, television, and digital media portals. It is a fast-paced, high-pressure career requiring strong ethics, a nose for news, and excellent communication skills.',
    category: 'Media & Communication',
    averageSalary: { entry: 250000, mid: 600000, senior: 1500000 },
    requiredSkills: ['Writing', 'Research', 'Interviewing', 'Ethics', 'Networking'],
    requiredEducation: ["BA in Journalism/Mass Comm", "PG Diploma in Journalism"],
    eligibility: '10+2 any stream. Strong command over English or regional languages.',
    entranceExams: ['IIMC Entrance', 'University Entrances (DU, Symbiosis)'],
    topColleges: ['IIMC Delhi', 'Asian College of Journalism (ACJ)', 'Symbiosis Institute of Media', 'Jamia Millia Islamia'],
    topCompanies: ['Times of India', 'NDTV', 'The Hindu', 'Network18', 'The Wire', 'Quint'],
    growthOutlook: 'Moderate',
    demandLevel: 'Moderate',
    workLifeBalance: 3,
    jobSatisfaction: 7,
    dayInLife: 'Chasing leads, conducting interviews, attending press conferences, writing articles against tight deadlines, and verifying facts.',
    riasecCodes: ['E', 'I', 'A'],
    roadmapSteps: [
      { step: 1, title: 'Foundation', description: 'Read newspapers. Start writing.', duration: '2 yrs', skills: ['General Knowledge'], resources: [] },
      { step: 2, title: 'Education', description: 'BA Journalism or Any degree.', duration: '3 yrs', skills: ['Writing'], resources: [] },
      { step: 3, title: 'PG Diploma', description: 'Optional but recommended PG at IIMC or ACJ.', duration: '1 yr', skills: ['Reporting'], resources: [] },
      { step: 4, title: 'Cub Reporter', description: 'Cover local beats.', duration: '2 yrs', skills: ['Source building'], resources: [] },
      { step: 5, title: 'Editor / Senior Anchor', description: 'Lead editorial teams or host prime-time shows.', duration: 'Ongoing', skills: ['Editorial Judgement'], resources: [] }
    ]
  },
  {
    title: 'Film Director',
    slug: 'film-director',
    shortDescription: 'Control a film\'s artistic and dramatic aspects and guide the crew.',
    description: 'Film Directors visualize the script and guide actors and the technical crew to bring that vision to the screen. Bollywood and regional cinema, along with the OTT boom in India, provide vast opportunities but the field is notoriously difficult to break into. It requires immense creative vision and people management skills.',
    category: 'Media & Communication',
    averageSalary: { entry: 0, mid: 1200000, senior: 10000000 },
    requiredSkills: ['Storytelling', 'Leadership', 'Visual Aesthetics', 'Cinematography basics', 'Crisis Management'],
    requiredEducation: ["Diploma/Degree in Filmmaking (Optional)"],
    eligibility: 'No strict academic requirements. Experience on film sets is mandatory.',
    entranceExams: ['FTII/SRFTI Entrance (JET)'],
    topColleges: ['FTII Pune', 'Satyajit Ray Film & Television Institute (SRFTI)', 'Whistling Woods International'],
    topCompanies: ['Dharma Productions', 'YRF', 'Netflix India', 'Independent Production'],
    growthOutlook: 'High (for OTT)',
    demandLevel: 'Competitive',
    workLifeBalance: 2,
    jobSatisfaction: 9,
    dayInLife: 'Pre-production planning, directing actors on set for 14 hours a day, sitting in dark rooms editing footage, and pitching scripts to producers.',
    riasecCodes: ['A', 'E', 'S'],
    roadmapSteps: [
      { step: 1, title: 'Foundation', description: 'Watch world cinema. Shoot short films on phone.', duration: '2 yrs', skills: ['Visual storytelling'], resources: [] },
      { step: 2, title: 'Film School (Optional)', description: 'Learn technical crafts.', duration: '2-3 yrs', skills: ['Camera', 'Editing'], resources: [] },
      { step: 3, title: 'Assistant Director (AD)', description: 'Work tirelessly as an AD on sets to learn the ropes.', duration: '3-5 yrs', skills: ['Set management'], resources: [] },
      { step: 4, title: 'Short Films / Ads', description: 'Direct independent short films or ad commercials.', duration: '2 yrs', skills: ['Directing'], resources: [] },
      { step: 5, title: 'Feature Film Directing', description: 'Pitch and direct a full-length feature or web series.', duration: 'Ongoing', skills: ['Vision execution'], resources: [] }
    ]
  },
  {
    title: 'Content Writer',
    slug: 'content-writer',
    shortDescription: 'Create engaging written content for digital marketing and publishing.',
    description: 'Content Writers produce engaging, relevant, and SEO-friendly copy for blogs, websites, social media, and whitepapers. In the digital economy, content is king. A good writer can work freelance or full-time for agencies and tech companies.',
    category: 'Media & Communication',
    averageSalary: { entry: 250000, mid: 600000, senior: 1200000 },
    requiredSkills: ['Copywriting', 'SEO', 'Research', 'Editing', 'Adaptability'],
    requiredEducation: ["Any Degree (English Literature/Mass Comm preferred)"],
    eligibility: 'Excellent writing skills and grammar.',
    entranceExams: ['None'],
    topColleges: ['Any (DU colleges for Literature are reputed)'],
    topCompanies: ['Marketing Agencies', 'SaaS Startups', 'Media Houses', 'Freelance Platforms'],
    growthOutlook: 'Steady',
    demandLevel: 'High',
    workLifeBalance: 7,
    jobSatisfaction: 7,
    dayInLife: 'Researching industry topics, writing blog posts, optimizing articles for Google search (SEO), editing drafts, and collaborating with graphic designers.',
    riasecCodes: ['A', 'I', 'C'],
    roadmapSteps: [
      { step: 1, title: 'Foundation', description: 'Read and write daily.', duration: '1 yr', skills: ['Grammar'], resources: [] },
      { step: 2, title: 'Learn SEO', description: 'Understand keywords and search intent.', duration: '3 months', skills: ['SEO basics'], resources: [] },
      { step: 3, title: 'Portfolio', description: 'Start a blog on Medium or WordPress.', duration: '6 months', skills: ['Writing'], resources: [] },
      { step: 4, title: 'Junior Writer', description: 'Join an agency. Learn brand voice.', duration: '2 yrs', skills: ['Adaptability'], resources: [] },
      { step: 5, title: 'Content Strategist', description: 'Plan content calendars and lead teams.', duration: 'Ongoing', skills: ['Strategy'], resources: [] }
    ]
  }
];
