export const medicalCareers = [
  {
    title: 'Doctor (MBBS)',
    slug: 'doctor-mbbs',
    shortDescription: 'Diagnose and treat illnesses, injuries, and health conditions.',
    description: 'A Doctor is a highly respected professional responsible for the health and well-being of patients. In India, becoming a doctor involves rigorous preparation starting from school, clearing the highly competitive NEET exam, and completing a 5.5-year MBBS degree followed by specialized MD/MS. They work in hospitals, private clinics, or community health centers. The profession demands immense dedication, long working hours, continuous learning, and a deep sense of empathy.',
    category: 'Medical & Healthcare',
    averageSalary: { entry: 600000, mid: 1500000, senior: 4000000 },
    requiredSkills: ['Medical Knowledge', 'Empathy', 'Decision Making', 'Stamina', 'Communication'],
    requiredEducation: ["MBBS", "MD/MS (Optional Specialization)"],
    eligibility: '10+2 with Physics, Chemistry, and Biology (PCB). Must clear NEET UG.',
    entranceExams: ['NEET UG', 'INI CET (for PG)', 'NEET PG'],
    topColleges: ['AIIMS Delhi', 'CMC Vellore', 'MAMC Delhi', 'KEM Mumbai', 'JIPMER', 'AFMC Pune'],
    topCompanies: ['Apollo Hospitals', 'Fortis Healthcare', 'Max Healthcare', 'Manipal Hospitals', 'Government Hospitals'],
    growthOutlook: 'Very High',
    demandLevel: 'Very High',
    workLifeBalance: 4,
    jobSatisfaction: 9,
    dayInLife: 'Conducting patient rounds, reviewing medical charts, prescribing treatments, performing procedures, staying updated on medical research, and handling emergencies.',
    riasecCodes: ['I', 'S', 'R'],
    roadmapSteps: [
      { step: 1, title: 'Foundation', description: 'Strong base in science subjects.', duration: '2 yrs', skills: ['Basic Biology'], resources: ['NCERT'] },
      { step: 2, title: 'Preparation', description: 'PCB focus and NEET prep.', duration: '2-3 yrs', skills: ['PCB', 'Time Management'], resources: ['Aakash/Allen modules'] },
      { step: 3, title: 'MBBS Education', description: '5.5 years including 1 yr internship.', duration: '5.5 yrs', skills: ['Anatomy', 'Clinical Skills'], resources: ['Medical textbooks'] },
      { step: 4, title: 'Early Career/PG Prep', description: 'Junior Resident or preparing for NEET PG.', duration: '1-3 yrs', skills: ['Patient Care'], resources: ['Marrow', 'Prepladder'] },
      { step: 5, title: 'Specialist', description: 'Complete MD/MS and practice as Specialist.', duration: 'Ongoing', skills: ['Specialized Surgery/Medicine'], resources: [] }
    ]
  },
  {
    title: 'Dentist',
    slug: 'dentist',
    shortDescription: 'Diagnose and treat problems related to teeth and gums.',
    description: 'Dentists specialize in oral health, treating issues related to teeth, gums, and the mouth. With rising awareness of oral hygiene and cosmetic dentistry, BDS graduates in India have growing opportunities both in urban clinics and teaching roles. It involves minor surgical procedures, prescribing medication, and educating patients on preventative oral care.',
    category: 'Medical & Healthcare',
    averageSalary: { entry: 300000, mid: 800000, senior: 2000000 },
    requiredSkills: ['Manual Dexterity', 'Attention to Detail', 'Patience', 'Clinical Skills'],
    requiredEducation: ["BDS", "MDS (Optional)"],
    eligibility: '10+2 with PCB. Admission through NEET UG.',
    entranceExams: ['NEET UG', 'NEET MDS'],
    topColleges: ['Maulana Azad Institute of Dental Sciences', 'Manipal College of Dental Sciences', 'Government Dental College Mumbai'],
    topCompanies: ['Clove Dental', 'Apollo White Dental', 'Private Clinics', 'Government Hospitals'],
    growthOutlook: 'Steady',
    demandLevel: 'High',
    workLifeBalance: 7,
    jobSatisfaction: 8,
    dayInLife: 'Examining patients\' teeth, performing root canals, extractions, fillings, taking X-rays, and advising on oral health.',
    riasecCodes: ['R', 'I', 'S'],
    roadmapSteps: [
      { step: 1, title: 'Foundation', description: 'Science focus.', duration: '2 yrs', skills: ['Biology'], resources: [] },
      { step: 2, title: 'Preparation', description: 'NEET UG prep.', duration: '2 yrs', skills: ['PCB'], resources: [] },
      { step: 3, title: 'Education', description: 'Complete BDS (4 yrs + 1 yr internship).', duration: '5 yrs', skills: ['Dental Surgery'], resources: [] },
      { step: 4, title: 'Early Career', description: 'Associate Dentist in a clinic or MDS prep.', duration: '2 yrs', skills: ['Patient handling'], resources: [] },
      { step: 5, title: 'Advanced', description: 'Own clinic or Senior Specialist.', duration: 'Ongoing', skills: ['Practice Management'], resources: [] }
    ]
  },
  {
    title: 'Pharmacist',
    slug: 'pharmacist',
    shortDescription: 'Dispense medications and provide expertise on their safe use.',
    description: 'Pharmacists are healthcare professionals specializing in the safe and effective use of medications. In India, the pharmaceutical sector is massive ("Pharmacy of the World"). Pharmacists work in retail pharmacies, hospitals, pharmaceutical manufacturing, quality control, and clinical research.',
    category: 'Medical & Healthcare',
    averageSalary: { entry: 250000, mid: 600000, senior: 1200000 },
    requiredSkills: ['Chemistry', 'Attention to Detail', 'Regulatory Knowledge', 'Communication'],
    requiredEducation: ["B.Pharm", "D.Pharm", "Pharm.D"],
    eligibility: '10+2 with PCM/PCB.',
    entranceExams: ['State Level Pharmacy Entrances (MHT CET, UPSEE)', 'GPAT (for M.Pharm)'],
    topColleges: ['Jamia Hamdard', 'Panjab University', 'NIPER Mohali', 'BITS Pilani', 'ICT Mumbai'],
    topCompanies: ['Sun Pharma', 'Cipla', 'Dr. Reddy\'s', 'Apollo Pharmacy', 'Biocon'],
    growthOutlook: 'Steady',
    demandLevel: 'High',
    workLifeBalance: 7,
    jobSatisfaction: 7,
    dayInLife: 'Dispensing prescriptions, advising patients on dosage/side effects, ensuring compliance with drug laws, or working in a lab testing drug formulations.',
    riasecCodes: ['I', 'C', 'S'],
    roadmapSteps: [
      { step: 1, title: 'Foundation', description: 'Basic sciences.', duration: '2 yrs', skills: ['Chemistry'], resources: [] },
      { step: 2, title: 'Preparation', description: '12th Science.', duration: '2 yrs', skills: ['PCB/PCM'], resources: [] },
      { step: 3, title: 'Education', description: 'B.Pharm degree.', duration: '4 yrs', skills: ['Pharmacology'], resources: [] },
      { step: 4, title: 'Early Career', description: 'Hospital/Retail Pharmacist or QA in pharma company.', duration: '2-3 yrs', skills: ['Dispensing'], resources: [] },
      { step: 5, title: 'Advanced', description: 'Pharma Management or Clinical Research.', duration: 'Ongoing', skills: ['Regulatory Affairs'], resources: [] }
    ]
  },
  {
    title: 'Biomedical Engineer',
    slug: 'biomedical-engineer',
    shortDescription: 'Design medical devices and equipment to improve healthcare.',
    description: 'Biomedical Engineers combine engineering principles with medical biological sciences to design and create equipment, devices, computer systems, and software used in healthcare. In India, with the rise of med-tech startups and government focus on indigenous medical device manufacturing, this field is growing.',
    category: 'Medical & Healthcare',
    averageSalary: { entry: 350000, mid: 900000, senior: 2000000 },
    requiredSkills: ['Engineering Design', 'Biology', 'Electronics', 'Problem Solving'],
    requiredEducation: ["B.Tech/B.E. Biomedical Engineering"],
    eligibility: '10+2 with PCM/PCB. (Math usually required for engineering admission).',
    entranceExams: ['JEE Main', 'State CETs', 'VITEEE'],
    topColleges: ['IIT Bombay', 'IIT BHU', 'NIT Rourkela', 'Manipal Institute of Technology'],
    topCompanies: ['Siemens Healthineers', 'GE Healthcare', 'Philips Healthcare', 'Medtronic', 'Johnson & Johnson'],
    growthOutlook: 'High',
    demandLevel: 'Steady',
    workLifeBalance: 7,
    jobSatisfaction: 8,
    dayInLife: 'Designing artificial organs, maintaining hospital machinery (MRI/CT scanners), ensuring safety standards of medical devices, and training staff to use equipment.',
    riasecCodes: ['I', 'R', 'C'],
    roadmapSteps: [
      { step: 1, title: 'Foundation', description: 'Math and Science.', duration: '2 yrs', skills: ['Math', 'Bio'], resources: [] },
      { step: 2, title: 'Preparation', description: 'JEE Prep.', duration: '2 yrs', skills: ['PCM'], resources: [] },
      { step: 3, title: 'Education', description: 'BTech Biomedical.', duration: '4 yrs', skills: ['Biomechanics', 'Electronics'], resources: [] },
      { step: 4, title: 'Early Career', description: 'Product Engineer or Hospital Maintenance.', duration: '3 yrs', skills: ['Equipment handling'], resources: [] },
      { step: 5, title: 'Advanced', description: 'R&D Head or MedTech Entrepreneur.', duration: 'Ongoing', skills: ['Innovation'], resources: [] }
    ]
  },
  {
    title: 'Clinical Psychologist',
    slug: 'clinical-psychologist',
    shortDescription: 'Assess, diagnose, and treat mental, emotional, and behavioral disorders.',
    description: 'Clinical Psychologists help clients overcome mental health issues, grief, trauma, and behavioral disorders through various therapies. With mental health awareness finally rising in India, the demand for qualified, RCI-licensed clinical psychologists is surging in hospitals, schools, and private practice.',
    category: 'Medical & Healthcare',
    averageSalary: { entry: 400000, mid: 900000, senior: 1800000 },
    requiredSkills: ['Active Listening', 'Empathy', 'Analytical Thinking', 'Communication', 'Patience'],
    requiredEducation: ["BA/BSc Psychology", "MA/MSc Psychology", "M.Phil Clinical Psychology (RCI approved)"],
    eligibility: '10+2 in any stream. BA/BSc followed by Masters and mandatory M.Phil for RCI license.',
    entranceExams: ['CUET (UG/PG)', 'NIMHANS Entrance', 'Institute level M.Phil Entrances'],
    topColleges: ['NIMHANS Bangalore', 'TISS Mumbai', 'Delhi University', 'Christ University', 'CIP Ranchi'],
    topCompanies: ['Vandrevala Foundation', 'Fortis Mental Health', 'Apollo Hospitals', 'Cure.fit', 'Private Practice'],
    growthOutlook: 'Very High',
    demandLevel: 'Very High',
    workLifeBalance: 6,
    jobSatisfaction: 9,
    dayInLife: 'Conducting therapy sessions (CBT, psychoanalysis), administering psychometric tests, writing patient reports, and collaborating with psychiatrists.',
    riasecCodes: ['S', 'I', 'A'],
    roadmapSteps: [
      { step: 1, title: 'Foundation', description: 'Any stream in 11/12th, preferably with Psychology.', duration: '2 yrs', skills: ['Empathy', 'Reading'], resources: [] },
      { step: 2, title: 'UG Education', description: 'Bachelors in Psychology.', duration: '3-4 yrs', skills: ['Basic Psychology Theories'], resources: [] },
      { step: 3, title: 'PG Education', description: 'Masters in Clinical/Applied Psychology.', duration: '2 yrs', skills: ['Research Methods'], resources: [] },
      { step: 4, title: 'M.Phil / Licensing', description: 'M.Phil to get RCI License to practice.', duration: '2 yrs', skills: ['Clinical Therapy', 'Diagnosis'], resources: [] },
      { step: 5, title: 'Practice', description: 'Hospital role or private practice.', duration: 'Ongoing', skills: ['CBT', 'Counseling'], resources: [] }
    ]
  },
  {
    title: 'Physiotherapist',
    slug: 'physiotherapist',
    shortDescription: 'Help patients manage pain and improve mobility through physical exercise.',
    description: 'Physiotherapists treat people with physical problems caused by illness, injury, disability, or ageing. In India, factors like sedentary tech jobs leading to back pain, sports injuries, and an aging population are driving the demand for skilled physiotherapists in hospitals and sports academies.',
    category: 'Medical & Healthcare',
    averageSalary: { entry: 250000, mid: 600000, senior: 1500000 },
    requiredSkills: ['Physical Stamina', 'Anatomy Knowledge', 'Empathy', 'Interpersonal Skills'],
    requiredEducation: ["Bachelor of Physiotherapy (BPT)", "Master of Physiotherapy (MPT)"],
    eligibility: '10+2 with PCB.',
    entranceExams: ['State level CETs', 'University specific entrance exams', 'IPU CET'],
    topColleges: ['CMC Vellore', 'Manipal College of Health Professions', 'Jamia Hamdard', 'KEM Mumbai'],
    topCompanies: ['Portea Medical', 'Sports Authority of India (SAI)', 'Apollo Hospitals', 'Religare Wellness'],
    growthOutlook: 'High',
    demandLevel: 'High',
    workLifeBalance: 7,
    jobSatisfaction: 8,
    dayInLife: 'Diagnosing physical abnormalities, designing customized exercise and massage routines, tracking patient progress, and educating patients on lifestyle changes.',
    riasecCodes: ['S', 'R', 'I'],
    roadmapSteps: [
      { step: 1, title: 'Foundation', description: 'Science stream in 12th.', duration: '2 yrs', skills: ['PCB'], resources: [] },
      { step: 2, title: 'Education', description: 'Complete BPT.', duration: '4.5 yrs', skills: ['Anatomy', 'Physiology', 'Exercise Therapy'], resources: [] },
      { step: 3, title: 'Internship', description: '6 months mandatory hospital internship.', duration: '6 months', skills: ['Patient Care'], resources: [] },
      { step: 4, title: 'Early Career', description: 'Junior Physiotherapist or MPT.', duration: '2 yrs', skills: ['Rehabilitation'], resources: [] },
      { step: 5, title: 'Advanced', description: 'Sports specialization or own clinic.', duration: 'Ongoing', skills: ['Advanced Therapies'], resources: [] }
    ]
  }
];
