export const businessCareers = [
  {
    title: 'Chartered Accountant',
    slug: 'chartered-accountant',
    shortDescription: 'Manage financial accounts, taxation, and auditing for businesses.',
    description: 'Chartered Accountants (CAs) are financial experts who manage accounting, auditing, taxation, and financial planning for corporations and individuals. It is one of the most prestigious and challenging qualifications in India, governed by the ICAI. CAs are essential for regulatory compliance, corporate governance, and strategic financial decision-making in any business.',
    category: 'Business & Finance',
    averageSalary: { entry: 800000, mid: 1800000, senior: 3500000 },
    requiredSkills: ['Accounting', 'Taxation Laws', 'Auditing', 'Analytical Skills', 'Attention to Detail'],
    requiredEducation: ["Chartered Accountancy (CA) via ICAI", "B.Com/M.Com (Usually pursued alongside CA)"],
    eligibility: '10+2 in any stream (Commerce preferred). Pass CA Foundation, Intermediate, and Final exams.',
    entranceExams: ['CA Foundation', 'CA Intermediate', 'CA Final'],
    topColleges: ['ICAI (Institute of Chartered Accountants of India)', 'SRCC Delhi (for B.Com)', 'Christ University'],
    topCompanies: ['Deloitte', 'PwC', 'EY', 'KPMG (The Big 4)', 'ITC', 'Reliance', 'HDFC Bank'],
    growthOutlook: 'Steady',
    demandLevel: 'High',
    workLifeBalance: 5,
    jobSatisfaction: 8,
    dayInLife: 'Auditing financial statements, filing tax returns, advising clients on tax saving strategies, analyzing financial reports, and ensuring compliance with GST and corporate laws.',
    riasecCodes: ['C', 'E', 'I'],
    roadmapSteps: [
      { step: 1, title: 'Foundation', description: '12th Commerce with Accounts and Math.', duration: '2 yrs', skills: ['Basic Accounting'], resources: ['TS Grewal Book'] },
      { step: 2, title: 'CA Foundation', description: 'Clear CA Foundation exam after 12th.', duration: '6 months', skills: ['Business Laws', 'Economics'], resources: ['ICAI modules'] },
      { step: 3, title: 'CA Intermediate', description: 'Clear Inter groups while doing B.Com.', duration: '1-2 yrs', skills: ['Taxation', 'Costing'], resources: ['Coaching classes'] },
      { step: 4, title: 'Articleship', description: '3 years of mandatory practical training under a practicing CA.', duration: '3 yrs', skills: ['Auditing', 'Practical Tax filing'], resources: ['On-job learning'] },
      { step: 5, title: 'CA Final', description: 'Clear Final exams to become a designated CA.', duration: '1 yr', skills: ['Advanced Financial Management'], resources: ['ICAI materials'] }
    ]
  },
  {
    title: 'Investment Banker',
    slug: 'investment-banker',
    shortDescription: 'Raise capital and advise on mergers and acquisitions for corporations.',
    description: 'Investment Bankers act as financial middlemen. They help companies, governments, and other entities raise capital through the issuance of stocks and bonds. They also provide strategic advice for mergers, acquisitions, and restructuring. Known for exceptionally high pay but intense working hours, it is a highly competitive field requiring an MBA from a top-tier B-School or an elite undergraduate degree.',
    category: 'Business & Finance',
    averageSalary: { entry: 1500000, mid: 4000000, senior: 10000000 },
    requiredSkills: ['Financial Modeling', 'Valuation', 'Negotiation', 'Excel Mastery', 'Networking'],
    requiredEducation: ["MBA in Finance", "B.Tech/B.A. Economics from Top Institutes", "CFA (Optional)"],
    eligibility: 'Top tier graduation followed by an MBA. Excellent quantitative and analytical skills.',
    entranceExams: ['CAT', 'XAT', 'GMAT'],
    topColleges: ['IIM Ahmedabad', 'IIM Bangalore', 'IIM Calcutta', 'ISB Hyderabad', 'FMS Delhi', 'SRCC'],
    topCompanies: ['Goldman Sachs', 'JP Morgan', 'Morgan Stanley', 'Avendus Capital', 'Kotak Mahindra Capital', 'Nomura'],
    growthOutlook: 'Moderate',
    demandLevel: 'High',
    workLifeBalance: 3,
    jobSatisfaction: 7,
    dayInLife: 'Building complex financial models in Excel, creating pitchbooks in PowerPoint, valuating companies, analyzing market trends, and long meetings with corporate clients.',
    riasecCodes: ['E', 'C', 'I'],
    roadmapSteps: [
      { step: 1, title: 'Foundation', description: 'Strong academics in school.', duration: '2 yrs', skills: ['Math'], resources: [] },
      { step: 2, title: 'Undergraduation', description: 'B.Tech from IIT or B.Com/Economics from SRCC/Stephen\'s.', duration: '3-4 yrs', skills: ['Quantitative analysis'], resources: [] },
      { step: 3, title: 'MBA Preparation', description: 'Crack CAT/GMAT with 99+ percentile.', duration: '1 yr', skills: ['Logic', 'Aptitude'], resources: ['TIME/CareerLauncher'] },
      { step: 4, title: 'MBA Finance', description: 'MBA from top IIM. Network heavily and secure summer internship.', duration: '2 yrs', skills: ['Corporate Finance'], resources: [] },
      { step: 5, title: 'IB Associate', description: 'Join as Associate. Survive the grueling hours to climb to VP/MD.', duration: 'Ongoing', skills: ['Deal making'], resources: [] }
    ]
  },
  {
    title: 'Management Consultant',
    slug: 'management-consultant',
    shortDescription: 'Solve complex business problems and improve organizational performance.',
    description: 'Management Consultants help companies improve their performance by analyzing existing organizational problems and developing plans for improvement. They work across various industries (strategy, operations, HR, IT). In India, consulting is a premier career choice for graduates from IITs and IIMs due to the diverse exposure, high compensation, and fast-tracked career progression.',
    category: 'Business & Finance',
    averageSalary: { entry: 1200000, mid: 3000000, senior: 6000000 },
    requiredSkills: ['Problem Solving', 'Data Analysis', 'Presentation Skills', 'Communication', 'Strategic Thinking'],
    requiredEducation: ["MBA", "B.Tech/B.A. Economics from Tier-1 institutions"],
    eligibility: 'Exceptional academic record. Strong logical reasoning and communication skills.',
    entranceExams: ['CAT', 'XAT', 'GMAT'],
    topColleges: ['IIMs', 'ISB Hyderabad', 'IITs (for undergraduate hiring)'],
    topCompanies: ['McKinsey & Co.', 'BCG', 'Bain & Co.', 'Accenture Strategy', 'Deloitte', 'KPMG'],
    growthOutlook: 'High',
    demandLevel: 'High',
    workLifeBalance: 4,
    jobSatisfaction: 8,
    dayInLife: 'Interviewing client employees, analyzing large datasets, brainstorming solutions with team members, creating slide decks, and presenting findings to C-level executives.',
    riasecCodes: ['E', 'I', 'S'],
    roadmapSteps: [
      { step: 1, title: 'Foundation', description: 'Maintain top grades.', duration: '2 yrs', skills: ['Communication'], resources: [] },
      { step: 2, title: 'Undergraduation', description: 'Get into a Tier-1 college. Take leadership roles in clubs.', duration: '3-4 yrs', skills: ['Case solving'], resources: ['CaseInPoint book'] },
      { step: 3, title: 'MBA or Analyst Role', description: 'Join directly as Analyst or do an MBA from a top B-School.', duration: '2 yrs', skills: ['Strategy frameworks'], resources: [] },
      { step: 4, title: 'Consultant', description: 'Travel to client sites, solve problems, manage workstreams.', duration: '2-3 yrs', skills: ['Stakeholder Management'], resources: [] },
      { step: 5, title: 'Partner / Exit', description: 'Become a Partner or exit to an industry leadership role.', duration: 'Ongoing', skills: ['Sales', 'Leadership'], resources: [] }
    ]
  },
  {
    title: 'Digital Marketing Manager',
    slug: 'digital-marketing-manager',
    shortDescription: 'Plan and execute online marketing campaigns and strategies.',
    description: 'Digital Marketing Managers oversee a company\'s online presence, utilizing SEO, social media, PPC, email marketing, and content strategies to drive traffic and sales. With India\'s internet penetration exploding, every brand needs a strong digital presence, making this a highly accessible and creative career path that doesn\'t strictly require elite degrees.',
    category: 'Business & Finance',
    averageSalary: { entry: 350000, mid: 900000, senior: 2000000 },
    requiredSkills: ['SEO/SEM', 'Google Analytics', 'Content Strategy', 'Social Media Management', 'Copywriting'],
    requiredEducation: ["Any Graduate", "MBA in Marketing (Optional)"],
    eligibility: 'No strict academic barrier. Skills, portfolio, and proven results matter more than degrees.',
    entranceExams: ['None strictly required (CAT for MBA Marketing)'],
    topColleges: ['MICA Ahmedabad', 'IIMs', 'Digital Marketing training institutes'],
    topCompanies: ['Ogilvy', 'Dentsu Webchutney', 'Amazon', 'Startups (Swiggy, Cred)', 'GroupM'],
    growthOutlook: 'Very High',
    demandLevel: 'Very High',
    workLifeBalance: 6,
    jobSatisfaction: 7,
    dayInLife: 'Analyzing website traffic, adjusting Google Ads bids, planning social media calendars, writing ad copy, and coordinating with designers for campaign assets.',
    riasecCodes: ['E', 'A', 'C'],
    roadmapSteps: [
      { step: 1, title: 'Foundation', description: 'Learn basics of social media and writing.', duration: '1 yr', skills: ['Communication'], resources: [] },
      { step: 2, title: 'Skill Building', description: 'Take online courses on SEO, Google Ads, and Meta Ads.', duration: '6 months', skills: ['SEO', 'PPC'], resources: ['HubSpot Academy', 'Google Garage'] },
      { step: 3, title: 'Internship/Freelance', description: 'Run small campaigns for local businesses or start a blog.', duration: '1 yr', skills: ['Execution', 'Data analysis'], resources: [] },
      { step: 4, title: 'Digital Marketer', description: 'Join an agency or startup as an executive. Manage campaigns.', duration: '2-3 yrs', skills: ['Campaign Management'], resources: [] },
      { step: 5, title: 'Marketing Head', description: 'Become an SEO expert, Performance Marketer, or CMO.', duration: 'Ongoing', skills: ['Budgeting', 'Strategy'], resources: [] }
    ]
  },
  {
    title: 'Product Manager',
    slug: 'product-manager',
    shortDescription: 'Guide the strategy, development, and launch of software products.',
    description: 'Product Managers (PMs) sit at the intersection of business, technology, and user experience (UX). They determine WHAT gets built by understanding user needs and business goals context, and work with engineers and designers to make it happen. It\'s one of the most coveted roles in the Indian tech ecosystem today, often called the "CEO of the product".',
    category: 'Business & Finance',
    averageSalary: { entry: 1000000, mid: 2500000, senior: 5000000 },
    requiredSkills: ['User Empathy', 'Data Analysis', 'Technical Acumen', 'Prioritization', 'Communication'],
    requiredEducation: ["B.Tech + MBA", "B.Tech (for APM roles)"],
    eligibility: 'Usually requires an engineering background or an MBA, though transitioning from design/marketing is possible.',
    entranceExams: ['CAT, GMAT (for MBA route)'],
    topColleges: ['ISB', 'IIMs', 'IITs'],
    topCompanies: ['Flipkart', 'Swiggy', 'Razorpay', 'Google', 'Microsoft', 'Atlassian', 'Zoho'],
    growthOutlook: 'Very High',
    demandLevel: 'High',
    workLifeBalance: 6,
    jobSatisfaction: 8,
    dayInLife: 'Writing product requirement documents (PRDs), conducting user interviews, prioritizing features in Jira, analyzing A/B test results, and aligning stakeholders.',
    riasecCodes: ['E', 'I', 'A'],
    roadmapSteps: [
      { step: 1, title: 'Foundation', description: 'Tech or Business degree.', duration: '3-4 yrs', skills: ['Critical Thinking'], resources: [] },
      { step: 2, title: 'Initial Experience', description: 'Work as a Software Engineer, Data Analyst, or Marketer.', duration: '2 yrs', skills: ['Domain Knowledge'], resources: [] },
      { step: 3, title: 'Transition', description: 'Get an MBA or transition internally to an Associate Product Manager (APM) role.', duration: '1-2 yrs', skills: ['Product Sense', 'Wireframing'], resources: ['Cracking the PM Interview'] },
      { step: 4, title: 'Product Manager', description: 'Manage a specific feature or product line.', duration: '2-3 yrs', skills: ['Roadmapping', 'Agile'], resources: [] },
      { step: 5, title: 'Product Leader', description: 'Become Group PM, VP of Product, or CPO.', duration: 'Ongoing', skills: ['Vision', 'Leadership'], resources: [] }
    ]
  },
  {
    title: 'Entrepreneur',
    slug: 'entrepreneur',
    shortDescription: 'Start and run new business ventures.',
    description: 'Entrepreneurs identify problems in the market, build products or services to solve them, raise capital, and build teams to scale the business. India is home to the world\'s 3rd largest startup ecosystem. While the financial risks are high, the potential upside and impact are unlimited. It requires immense resilience, risk tolerance, and sheer hustle.',
    category: 'Business & Finance',
    averageSalary: { entry: 0, mid: 1200000, senior: 10000000 }, // Highly variable
    requiredSkills: ['Leadership', 'Risk Management', 'Sales/Pitching', 'Resilience', 'Vision'],
    requiredEducation: ["Any Degree (or None)"],
    eligibility: 'Zero academic requirements. High tolerance for failure and risk.',
    entranceExams: ['None'],
    topColleges: ['Any (IITs/IIMs provide better networking for funding)'],
    topCompanies: ['Your Own Startup', 'Y Combinator', 'Sequoia Surge'],
    growthOutlook: 'Exponential',
    demandLevel: 'N/A',
    workLifeBalance: 2,
    jobSatisfaction: 9,
    dayInLife: 'Pitching to investors, talking to customers, hiring talent, fixing urgent fires, managing cash flow, and iterating on the product.',
    riasecCodes: ['E', 'A', 'S'],
    roadmapSteps: [
      { step: 1, title: 'Identify Problem', description: 'Find a problem you are passionate about solving.', duration: 'Variable', skills: ['Observation'], resources: [] },
      { step: 2, title: 'Market Validation', description: 'Talk to potential customers. Build an MVP (Minimum Viable Product).', duration: '3-6 months', skills: ['Prototyping', 'Sales'], resources: ['The Lean Startup'] },
      { step: 3, title: 'Early Traction', description: 'Get your first 100 paying customers. Iterate based on feedback.', duration: '1 yr', skills: ['Marketing', 'Resilience'], resources: [] },
      { step: 4, title: 'Fundraising & Scaling', description: 'Raise Seed/Series A funding from VCs to scale operations.', duration: '1-2 yrs', skills: ['Pitching', 'Financial Planning'], resources: [] },
      { step: 5, title: 'Growth', description: 'Hire executives, expand to new markets, aim for profitability or IPO.', duration: 'Ongoing', skills: ['Leadership', 'Delegation'], resources: [] }
    ]
  }
];
