export const otherCareers = [
  {
    title: 'IAS Officer (Civil Services)',
    slug: 'ias-officer',
    shortDescription: 'Administer government policies, manage districts, and lead public sector enterprises.',
    description: 'An Indian Administrative Service (IAS) Officer is the most prestigious government job in India. They hold key positions in the Union and State governments, District administration, and Public Sector Undertakings. Clearing the UPSC Civil Services Examination (CSE) is famously one of the toughest academic challenges globally, with a massive syllabus and fierce competition. IAS officers have unparalleled authority to impact society and implement policies at the grassroots.',
    category: 'Government & Defence',
    averageSalary: { entry: 672000, mid: 1200000, senior: 3000000 }, // Plus perks like housing/car
    requiredSkills: ['Leadership', 'Decision Making', 'Extensive Knowledge Base', 'Resilience', 'Public Administration'],
    requiredEducation: ["Any Bachelor's Degree"],
    eligibility: 'Must hold a graduate degree. Must clear UPSC CSE Prelims, Mains, and Interview.',
    entranceExams: ['UPSC CSE Prelims', 'UPSC CSE Mains', 'UPSC Interview'],
    topColleges: ['LBSNAA Mussoorie (training)', 'Any graduate degree from a recognized university'],
    topCompanies: ['Government of India', 'State Governments', 'Various Ministries'],
    growthOutlook: 'Steady',
    demandLevel: 'Highly Competitive',
    workLifeBalance: 4,
    jobSatisfaction: 9,
    dayInLife: 'Reviewing government files and policies, inspecting government schools/hospitals, meeting with politicians, handling law and order situations during riots, and attending marathon administrative meetings.',
    riasecCodes: ['E', 'I', 'S'],
    roadmapSteps: [
      { step: 1, title: 'Foundation', description: 'Read newspapers (The Hindu/Indian Express) daily.', duration: 'School', skills: ['General Knowledge', 'Current Affairs'], resources: [] },
      { step: 2, title: 'Graduation', description: 'Complete a bachelor\'s degree. Begin NCERT book readings (Class 6-12).', duration: '3-4 yrs', skills: ['Discipline', 'Extensive Reading'], resources: ['NCERT Textbooks'] },
      { step: 3, title: 'Dedicated Preparation', description: 'At least one year of full-time study covering history, polity, geography, ethics, optional subject.', duration: '1-2 yrs', skills: ['Answer Writing'], resources: ['M. Laxmikanth (Polity)', 'Spectrum (History)'] },
      { step: 4, title: 'UPSC Examination', description: 'Clear Prelims (MCQ), Mains (Descriptive), and the grueling Personality Test.', duration: '1 yr', skills: ['Stress Management', 'Interviewing'], resources: ['Vajiram & Ravi notes'] },
      { step: 5, title: 'Training & Posting', description: '2 years of training at LBSNAA and Bharat Darshan before first district posting as SDM.', duration: '2 yrs', skills: ['Administration'], resources: [] }
    ]
  },
  {
    title: 'Defence Officer (Indian Armed Forces)',
    slug: 'defence-officer',
    shortDescription: 'Lead and command troops to defend the nation\'s sovereignty.',
    description: 'Serving as an officer in the Indian Army, Navy, or Air Force is a career of immense pride, honor, and adventure. It demands extreme physical fitness, courage, and leadership under life-threatening pressure. Officers gain unparalleled discipline, lifelong camaraderie, and opportunities to serve on the frontiers, fly fighter jets, or command warships.',
    category: 'Government & Defence',
    averageSalary: { entry: 1000000, mid: 1800000, senior: 3000000 }, // Generous allowances, medical, housing
    requiredSkills: ['Physical Fitness', 'Courage', 'Leadership (OLQs - Officer Like Qualities)', 'Teamwork', 'Quick Decision Making'],
    requiredEducation: ["Undergraduate Degree (for CDS/AFCAT)", "10+2 (for NDA)"],
    eligibility: 'Varies by entry scheme. 10+2 (PCM) required for Navy/Air Force. Any stream for Army. Must clear SSB Interview and Medicals.',
    entranceExams: ['NDA', 'CDS', 'AFCAT', 'SSB Interview (5-day process)'],
    topColleges: ['National Defence Academy (NDA)', 'Indian Military Academy (IMA)', 'Air Force Academy (AFA)', 'Indian Naval Academy (INA)'],
    topCompanies: ['Indian Army', 'Indian Navy', 'Indian Air Force', 'Indian Coast Guard'],
    growthOutlook: 'Steady',
    demandLevel: 'Highly Competitive',
    workLifeBalance: 3,
    jobSatisfaction: 10,
    dayInLife: 'Leading physical training drills, inspecting weapon maintenance, planning tactical operations, participating in counter-insurgency ops or border patrols.',
    riasecCodes: ['R', 'E', 'S'],
    roadmapSteps: [
      { step: 1, title: 'Foundation', description: 'Maintain excellent physical fitness and participate in sports/NCC.', duration: 'School', skills: ['Discipline'], resources: ['NCC Cadets'] },
      { step: 2, title: 'Preparation', description: 'Prepare for NDA/CDS written exams (Math, English, GK).', duration: '1-2 yrs', skills: ['Aptitude', 'Physical Stamina'], resources: [] },
      { step: 3, title: 'SSB Interview', description: 'Clear the 5-day psychological and physical assessment at the Services Selection Board.', duration: '1 week', skills: ['OLQs', 'Group Tasks'], resources: [] },
      { step: 4, title: 'Academy Training', description: 'Grueling military training at NDA/IMA/AFA to transform a cadet into an officer.', duration: '1-4 yrs', skills: ['Weaponry', 'Tactics', 'Leadership'], resources: [] },
      { step: 5, title: 'Commissioning', description: 'Commissioned as Lieutenant/Sub-Lieutenant/Flying Officer to lead a platoon or squadron.', duration: 'Ongoing', skills: ['Command Line'], resources: [] }
    ]
  },
  {
    title: 'Environmental Scientist',
    slug: 'environmental-scientist',
    shortDescription: 'Analyze environmental problems and develop solutions to protect nature.',
    description: 'Environmental Scientists use their knowledge of natural sciences to protect the environment and human health. In India, tackling extreme pollution, water scarcity, and climate change is an urgent necessity. They work with NGOs, government agencies (like CPCB), and corporations to ensure sustainable practices, perform Environmental Impact Assessments (EIA), and develop waste management solutions.',
    category: 'Emerging & Non-Traditional',
    averageSalary: { entry: 400000, mid: 900000, senior: 2000000 },
    requiredSkills: ['Data Collection', 'GIS/Remote Sensing', 'Analytical Thinking', 'Ecology', 'Policy Knowledge'],
    requiredEducation: ["B.Sc Environmental Science", "M.Sc/M.Tech Environmental Engineering/Science"],
    eligibility: '10+2 Science (PCB or PCM). Must have a strong affinity for nature and research.',
    entranceExams: ['CUET', 'GATE (for M.Tech)'],
    topColleges: ['TERI School of Advanced Studies', 'JNU', 'Forest Research Institute Dehradun', 'IITs (for M.Tech)'],
    topCompanies: ['Central Pollution Control Board', 'WWF India', 'TERI', 'CSIR NEERI', 'Corporate ESG Teams'],
    growthOutlook: 'High',
    demandLevel: 'High',
    workLifeBalance: 7,
    jobSatisfaction: 8,
    dayInLife: 'Collecting water/soil samples from field sites, analyzing chemical compositions in labs, writing EIA reports for new construction projects, and advising industries on reducing their carbon footprint.',
    riasecCodes: ['I', 'R', 'C'],
    roadmapSteps: [
      { step: 1, title: 'Foundation', description: 'Strong interest in biology, chemistry, and geography.', duration: '2 yrs', skills: ['Observation'], resources: [] },
      { step: 2, title: 'Undergraduate', description: 'B.Sc in Environmental Science, Botany, or Zoology.', duration: '3-4 yrs', skills: ['Field Work', 'Lab techniques'], resources: [] },
      { step: 3, title: 'Postgraduate', description: 'M.Sc or M.Tech to specialize in ecology, GIS, or policy.', duration: '2 yrs', skills: ['Data Modeling', 'GIS software'], resources: [] },
      { step: 4, title: 'Early Career', description: 'Join as a Research Assistant or Field Officer in an NGO or consultancy.', duration: '2 yrs', skills: ['Report Writing'], resources: [] },
      { step: 5, title: 'Senior Scientist / Consultant', description: 'Lead massive environmental conservation projects or ESG corporate audits.', duration: 'Ongoing', skills: ['Project Management'], resources: [] }
    ]
  },
  {
    title: 'Sports Manager',
    slug: 'sports-manager',
    shortDescription: 'Handle the business and management side of sports organizations or athletes.',
    description: 'Sports Management is a booming field in India outside of traditional playing roles. With the success of cricket (IPL) and rising leagues in Kabaddi, Football (ISL), and badminton, the industry needs professionals to manage athlete PR, stadium operations, sponsorships, event marketing, and sports analytics.',
    category: 'Emerging & Non-Traditional',
    averageSalary: { entry: 300000, mid: 800000, senior: 3000000 },
    requiredSkills: ['Networking', 'Marketing', 'Negotiation', 'Event Management', 'Passion for Sports'],
    requiredEducation: ["BBA/MBA in Sports Management", "Any Degree + Experience"],
    eligibility: 'Any stream in 10+2. A deep understanding of sports ecosystems is required.',
    entranceExams: ['SMAT (Sports Management Admission Test)', 'CAT (for general MBA)'],
    topColleges: ['IISM Mumbai', 'Symbiosis School of Sports Sciences', 'NASM'],
    topCompanies: ['BCCI', 'Reliance Sports (IMG-Reliance)', 'Dream11', 'JSW Sports', 'Star Sports'],
    growthOutlook: 'Very High',
    demandLevel: 'Moderate to High',
    workLifeBalance: 4,
    jobSatisfaction: 8,
    dayInLife: 'Pitching sponsorship decks to brands, negotiating player contracts, organizing logistics for a sports league match, or analyzing fan engagement data.',
    riasecCodes: ['E', 'S', 'C'],
    roadmapSteps: [
      { step: 1, title: 'Foundation', description: 'Play sports or intensely follow sports leagues and their business models.', duration: 'School', skills: ['Sports Knowledge'], resources: [] },
      { step: 2, title: 'Undergraduate Course', description: 'Get a BBA in Sports Management or a general BBA/B.Com.', duration: '3 yrs', skills: ['Business Basics'], resources: [] },
      { step: 3, title: 'Volunteering/Internship', description: 'Volunteer at marathons, IPL matches, or local sporting events to build a network.', duration: '1-2 yrs', skills: ['Event execution', 'Networking'], resources: [] },
      { step: 4, title: 'Sports MBA (Optional)', description: 'Specialize in sports marketing or analytics via an MBA.', duration: '2 yrs', skills: ['Sports Law', 'Analytics'], resources: [] },
      { step: 5, title: 'Management Professional', description: 'Work for sports franchises, agencies, or broadcasters managing operations/talent.', duration: 'Ongoing', skills: ['Deal making'], resources: [] }
    ]
  },
  {
    title: 'Chef / Culinary Arts',
    slug: 'chef',
    shortDescription: 'Prepare food professionally and manage kitchen operations.',
    description: 'A Chef is more than just a cook. They are culinary artists and kitchen managers. The food and beverage (F&B) industry in India is massive, with opportunities in 5-star hotels, luxury cruise ships, cloud kitchens, and starting independent restaurants or cafes. It demands extreme physical stamina, creativity, and working during holidays when everyone else is celebrating.',
    category: 'Emerging & Non-Traditional',
    averageSalary: { entry: 200000, mid: 600000, senior: 2500000 }, // Celebrity chefs earn vastly more
    requiredSkills: ['Cooking Techniques', 'Palate/Tasting', 'Time Management', 'Leadership', 'Hygiene Standards'],
    requiredEducation: ["B.Sc in Hotel Management", "Diploma in Culinary Arts"],
    eligibility: '10+2 in any stream. Passion for food is the ultimate prerequisite.',
    entranceExams: ['NCHMCT JEE', 'Institute Level Entrances'],
    topColleges: ['IHMs (Pusa Delhi, Mumbai, Aurangabad)', 'Welcomgroup Graduate School of Hotel Administration (WGSHA) Manipal', 'Le Cordon Bleu India'],
    topCompanies: ['Taj Hotels (IHCL)', 'Oberoi Group', 'ITC Hotels', 'Massive Restaurants', 'Cloud Kitchens like Curefoods'],
    growthOutlook: 'Steady',
    demandLevel: 'High',
    workLifeBalance: 3,
    jobSatisfaction: 8,
    dayInLife: 'Arriving early to manage inventory, prepping ingredients, cooking under massive pressure during lunch/dinner rushes, inventing new menu items, and managing the kitchen brigade (sous chefs, line cooks).',
    riasecCodes: ['R', 'A', 'E'],
    roadmapSteps: [
      { step: 1, title: 'Foundation', description: 'Experiment with cooking at home. Understand flavors and ingredients.', duration: 'School', skills: ['Palate', 'Basic Cooking'], resources: [] },
      { step: 2, title: 'Hotel Management Degree', description: 'Clear NCHMCT JEE and enroll in a reputed IHM. Learn all aspects (F&B, Front office, Kitchen).', duration: '3-4 yrs', skills: ['Food theory', 'Technique'], resources: [] },
      { step: 3, title: 'Industrial Training', description: '6 months of grueling kitchen internship in a 5-star hotel.', duration: '6 months', skills: ['Speed', 'Resilience'], resources: [] },
      { step: 4, title: 'Commis Chef', description: 'Start at the bottom rung. Chop vegetables, make sauces, learn the station.', duration: '2-4 yrs', skills: ['Consistency', 'Knife skills'], resources: [] },
      { step: 5, title: 'Sous Chef / Executive Chef', description: 'Manage the entire kitchen, design menus, and control food costs.', duration: 'Ongoing', skills: ['Menu Engineering', 'Kitchen Management'], resources: [] }
    ]
  },
  {
    title: 'Airline Pilot',
    slug: 'airline-pilot',
    shortDescription: 'Fly commercial aircraft to transport passengers and cargo safely.',
    description: 'Commercial Airline Pilots have one of the most glamorous, high-responsibility, and highly paid jobs in the world. In India, the aviation sector is expanding rapidly (IndiGo, Air India bulk orders). However, the training is extremely expensive (₹50L to ₹1Cr). It requires impeccable health, perfect vision (with or without glasses), quick reflexes, and the ability to stay calm during emergencies.',
    category: 'Emerging & Non-Traditional',
    averageSalary: { entry: 1800000, mid: 3600000, senior: 8000000 },
    requiredSkills: ['Spatial Awareness', 'Calm under pressure', 'Communication', 'Technical Aircraft Knowledge', 'Weather analysis'],
    requiredEducation: ["Commercial Pilot License (CPL)"],
    eligibility: '10+2 with Physics and Mathematics is mandatory. Must pass stringent Class 1 Medical tests by DGCA.',
    entranceExams: ['IGRUAA Entrance', 'NDA (for Air Force pilots)', 'Cadet Pilot Program Entrances (IndiGo/Air India)'],
    topColleges: ['IGRUA Amethi', 'Chimes Aviation Academy', 'CAE Oxford (Cadet programs)', 'Flying Clubs in US/Canada/New Zealand'],
    topCompanies: ['IndiGo', 'Air India', 'Vistara', 'SpiceJet', 'Akasa Air', 'Emirates/Qatar (Global)'],
    growthOutlook: 'High',
    demandLevel: 'High',
    workLifeBalance: 4,
    jobSatisfaction: 9,
    dayInLife: 'Reviewing weather reports, performing pre-flight aircraft checks, coordinating with air traffic control (ATC), flying the plane (often on autopilot during cruise), and navigating treacherous weather or instrument landings.',
    riasecCodes: ['R', 'I', 'C'],
    roadmapSteps: [
      { step: 1, title: 'Foundation & Medicals', description: 'Take PCM in 11th. Crucially, clear the DGCA Class 2 and Class 1 medical examinations before investing money.', duration: '2 yrs', skills: ['Physics', 'Math', 'Perfect Medical Health'], resources: ['DGCA Doctors list'] },
      { step: 2, title: 'Entrance Exams', description: 'Join a Cadet Pilot Program (guaranteed job but expensive) or clear IGRUAA entrance.', duration: '6 months', skills: ['Aptitude', 'Psychometric'], resources: [] },
      { step: 3, title: 'Ground School', description: 'Pass grueling theoretical exams on Navigation, Meteorology, Air Regulations, and Aircraft Technicals conducted by DGCA.', duration: '6-12 months', skills: ['Aviation Theory', 'Meteorology'], resources: [] },
      { step: 4, title: 'Flight Training', description: 'Log 200 hours of flight time in a single/multi-engine Cessna to earn the CPL (Commercial Pilot License).', duration: '1-2 yrs', skills: ['Flying skills', 'Radio Communication'], resources: [] },
      { step: 5, title: 'Type Rating & First Officer', description: 'Pay for and complete Type Rating on an Airbus A320 or Boeing 737. Join an airline as First Officer (Co-pilot).', duration: 'Ongoing', skills: ['Jet handling'], resources: [] }
    ]
  }
];
